# debut config d'origine
# controllers:
#     resource: ../src/Controller/
#     type: annotation

# kernel:
#     resource: ../src/Kernel.php
#     type: annotation
# fin config d'origine


#debut config
home:
    path: /
    controller: App\Controller\HomeController::index