controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#debut modif
home:
    path: /
    controller: App\Controller\DefaultController::index